### ISSUE TITLE
primus: do not run Analysis on unchecked (i.e. not visible) data

### ISSUE THREAD

**Issue by plmnnk** [biosaxs-com/atsas-community#1940] opened 2024-09-05 10:48 UTC
Start PRIMUS. Go to File > Open Data Files, open any two .dat files. In the right panel (under Documents > Filename) uncheck the second file and click Analysis > Radius of Gyration. The Guinier Wizard opens the _second_ file that we just unchecked and that was not made active (when the line with Filename becomes dark blue). This is very confusing and leads to mistakes in data analysis.
It would be better not to run any Analysis wizards on any unchecked data (like the Processing tools don't run on unchecked data).

I know that in the first step of the wizard the full path to the file is shown. But I don't think that the users will remember all their filenames and will check that full path every time they want to estimate the Rg. Besides it allows only .dat and .out files and it is not possible to run any wizard on e.g. an .abs file. Would it make sense to remove this filename verification step?

**Comment by franke-biosaxs** [comment] 2024-09-18 08:36
> Start PRIMUS. Go to File > Open Data Files, open any two .dat files. In the right panel (under Documents > Filename) uncheck the second file and click Analysis > Radius of Gyration. The Guinier Wizard opens the _second_ file that we just unchecked and that was not made active (when the line with Filename becomes dark blue). 

When you say "click Analysis > Radius of Gyration" you refer to the toolbar or main menu bar? If so, then the Wizard does not open the second file, but the file name given - that defaults to the second file. Note the "Browse" button. The point of toolbar and main menu is to be able to potentially open any file in the wizard, not just whatever is open in the main view. Right click on the documents entry and the wizard opens _that_ particular file, even if it is not currently shown in the main plot. Because why does it need to be shown in the main plot to be used in the wizard?

Example for ab initio: 
 1. in the toolbar, click "Ab initio modelling", select an .out file. No need for Rg/Dmax, directly to modelling options
 2. in the documents, right click a .dat file and select "Ab initio modelling". Go through Rg/Dmax, then modelling options

IMO, it all works as intended?

**Comment by franke-biosaxs** [comment] 2024-09-23 06:49
No further feedback. Closing.

**Closed by franke-biosaxs** 2024-09-23 06:49 UTC
